# POST https://graph.zalo.me/v2.0/me/message?access_token=<USER_ACCESS_TOKEN>&message=testcase&link=https://developers.zalo.me/&to=friend_id"

GET https://oauth.zaloapp.com/v3/auth?app_id=455815796857639408&redirect_uri={2}&state={3}
